name: repository_file

on: [push]

jobs:
    Task-3:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout
            - run: echo ${BRANCH_NAME}
            - run: du -skh --exclude=".git"