name: repository_file

on: [push]

jobs:
    Task-3:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "${GITHUB_REF}"
            - run: du -skh --exclude=".git"